apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - name: {{ .Values.app_name }}
        image: {{ .Values.container.registry}}{{ .Values.container.image }}:{{ .Values.container.tag }}
        ports:
        - containerPort: 8080
          protocol: TCP