{{- if not .Values.app_secret.secretKeyBase.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}-secret-key
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  secret-key-base: ""
{{- end }}
