{{- if not .Values.postgresql.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}-db
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.bundled.primary.password | default "sure_password" | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.database | b64enc }}
{{- end }}
