{{- if and .Values.backup.enabled (not .Values.backup.passwordSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}-backup-db
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.bundled.primary.password | default "sure_password" | b64enc }}
{{- end }}
